In [28]:
#data import and convert to data frame
import pandas as pd

df=pd.read_csv('air-pollution.csv')
print(df)

            Entity Code  Year  Nitrogen oxide (NOx)  \
0      Afghanistan  AFG  1750             555.47860
1      Afghanistan  AFG  1760             578.50757
2      Afghanistan  AFG  1770             602.47980
3      Afghanistan  AFG  1780             627.43220
4      Afghanistan  AFG  1790             653.40310
...            ...  ...   ...                   ...
48220     Zimbabwe  ZWE  2018           82210.49000
48221     Zimbabwe  ZWE  2019           79547.03000
48222     Zimbabwe  ZWE  2020           68338.91400
48223     Zimbabwe  ZWE  2021           71148.93000
48224     Zimbabwe  ZWE  2022           73363.71000

       Sulphur dioxide (SO₂) emissions  Carbon monoxide (CO) emissions  \
0                            174.87167                       142073.31
1                            181.99332                       147859.23
2                            189.38850                       153867.40
3                            197.06535                       160104.42
4                            205.03189                       166576.77
...                                ...                             ...
48220                      56748.18400                      1557296.50
48221                      53065.87500                      1574731.90
48222                      43894.06000                      1593834.00
48223                      45291.41800                      1624286.00
48224                      51669.65000                      1626256.20

       Organic carbon (OC) emissions  \
0                          5456.8850
1                          5679.1167
2                          5909.8840
3                          6149.4410
4                          6398.0370
...                              ...
48220                    111642.5100
48221                    113660.8600
48222                    115329.2340
48223                    117177.1950
48224                    117211.6800

       Non-methane volatile organic compounds (NMVOC) emissions  \
0                                              13596.633
1                                              14150.870
2                                              14726.470
3                                              15324.077
4                                              15944.332
...                                                  ...
48220                                         291050.400
48221                                         294380.620
48222                                         298699.940
48223                                         304488.380
48224                                         305560.900

       Black carbon (BC) emissions  Ammonia (NH₃) emissions  Unnamed: 10
0                        1633.0308                7681.0464          NaN
1                        1699.5359                8000.8574          NaN
2                        1768.5956                8333.9610          NaN
3                        1840.2854                8680.9060          NaN
4                        1914.6805                9042.2660          NaN
...                            ...                      ...          ...
48220                   32050.9020              124543.0160          NaN
48221                   32552.8750              127205.2700          NaN
48222                   32467.2950              129910.9300          NaN
48223                   33174.6050              132651.4800          NaN
48224                   33231.3200              134480.5800          NaN

[48225 rows x 11 columns]

In [2]:
print(df.describe())

               Year  Nitrogen oxide (NOx)  Sulphur dioxide (SO₂) emissions  \
count  48225.000000          4.822500e+04                     4.822500e+04
mean    1911.032970          5.407779e+05                     8.091183e+05
std       67.608974          4.408950e+06                     5.761058e+06
min     1750.000000          0.000000e+00                     0.000000e+00
25%     1854.000000          1.569637e+02                     6.362120e+01
50%     1913.000000          1.781608e+03                     9.523438e+02
75%     1970.000000          3.104208e+04                     3.370849e+04
max     2022.000000          1.092431e+08                     1.345966e+08

       Carbon monoxide (CO) emissions  Organic carbon (OC) emissions  \
count                    4.822500e+04                   4.822500e+04
mean                     4.885731e+06                   1.315203e+05
std                      2.851080e+07                   6.740897e+05
min                      0.000000e+00                   0.000000e+00
25%                      1.367615e+04                   5.955074e+02
50%                      1.087148e+05                   4.429489e+03
75%                      6.107858e+05                   2.220716e+04
max                      5.999133e+08                   1.361832e+07

       Non-methane volatile organic compounds (NMVOC) emissions  \
count                                       4.822500e+04
mean                                        8.771926e+05
std                                         5.769500e+06
min                                         0.000000e+00
25%                                         2.313765e+03
50%                                         1.770346e+04
75%                                         1.132467e+05
max                                         1.354817e+08

       Black carbon (BC) emissions  Ammonia (NH₃) emissions  Unnamed: 10
count                 4.822500e+04             4.822500e+04          0.0
mean                  4.738836e+04             3.521420e+05          NaN
std                   2.769505e+05             2.326560e+06          NaN
min                   0.000000e+00             0.000000e+00          NaN
25%                   1.490397e+02             1.370903e+03          NaN
50%                   1.090644e+03             9.434461e+03          NaN
75%                   6.594997e+03             5.192593e+04          NaN
max                   6.141969e+06             6.394764e+07          NaN

In [29]:
#clean data rows empty
cleaned_df = df.dropna(how="all")

In [30]:
# Replace null values with 0
cleaned_df = cleaned_df.fillna(0)

In [31]:
#remove duplicate entities
cleaned_df.drop_duplicates(inplace=True)

In [32]:
# Calculate median, mean, and standard deviation for 'Nitrogen oxide (NOx)' and add them as new columns
cleaned_df['NOx_median'] = cleaned_df['Nitrogen oxide (NOx)'].median()
cleaned_df['NOx_mean'] = cleaned_df['Nitrogen oxide (NOx)'].mean()
cleaned_df['NOx_std'] = cleaned_df['Nitrogen oxide (NOx)'].std()

In [34]:
cleaned_df['SO₂_median'] = cleaned_df['Sulphur dioxide (SO₂) emissions'].median()
cleaned_df['SO₂_mean'] = cleaned_df['Sulphur dioxide (SO₂) emissions'].mean()
cleaned_df['SO₂_std'] = cleaned_df['Sulphur dioxide (SO₂) emissions'].std()

In [35]:
#for printing table
cleaned_df

,Entity,Code,Year,Nitrogen oxide (NOx),Sulphur dioxide (SO₂) emissions,Carbon monoxide (CO) emissions,Organic carbon (OC) emissions,Non-methane volatile organic compounds (NMVOC) emissions,Black carbon (BC) emissions,Ammonia (NH₃) emissions,Unnamed: 10,NOx_median,NOx_mean,NOx_std,SO₂_median,SO₂_mean,SO₂_std
0,Afghanistan,AFG,1750,555.47860,174.87167,142073.31,5456.8850,13596.633,1633.0308,7681.0464,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
1,Afghanistan,AFG,1760,578.50757,181.99332,147859.23,5679.1167,14150.870,1699.5359,8000.8574,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
2,Afghanistan,AFG,1770,602.47980,189.38850,153867.40,5909.8840,14726.470,1768.5956,8333.9610,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
3,Afghanistan,AFG,1780,627.43220,197.06535,160104.42,6149.4410,15324.077,1840.2854,8680.9060,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
4,Afghanistan,AFG,1790,653.40310,205.03189,166576.77,6398.0370,15944.332,1914.6805,9042.2660,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48220,Zimbabwe,ZWE,2018,82210.49000,56748.18400,1557296.50,111642.5100,291050.400,32050.9020,124543.0160,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
48221,Zimbabwe,ZWE,2019,79547.03000,53065.87500,1574731.90,113660.8600,294380.620,32552.8750,127205.2700,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
48222,Zimbabwe,ZWE,2020,68338.91400,43894.06000,1593834.00,115329.2340,298699.940,32467.2950,129910.9300,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
48223,Zimbabwe,ZWE,2021,71148.93000,45291.41800,1624286.00,117177.1950,304488.380,33174.6050,132651.4800,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06
48224,Zimbabwe,ZWE,2022,73363.71000,51669.65000,1626256.20,117211.6800,305560.900,33231.3200,134480.5800,0.0,1781.6083,540777.937547,4.408950e+06,952.34375,809118.254467,5.761058e+06

In [26]:
# Create a filter based on the country column
country_filter = cleaned_df['Entity'].isin(['Qatar', 'India'])
filtered_df = cleaned_df[country_filter]
filtered_df

,Entity,Code,Year,Nitrogen oxide (NOx),Sulphur dioxide (SO₂) emissions,Carbon monoxide (CO) emissions,Organic carbon (OC) emissions,Non-methane volatile organic compounds (NMVOC) emissions,Black carbon (BC) emissions,Ammonia (NH₃) emissions,Unnamed: 10,NOx_median,NOx_mean,NOx_std
19475,India,IND,1750,30488.506,34813.883,8360133.50,416970.56000,964998.75,122179.0550,479372.880,0.0,1781.6083,540777.937547,4.408950e+06
19476,India,IND,1760,31085.959,35436.080,8509232.00,424385.12000,982068.06,124343.6700,488997.530,0.0,1781.6083,540777.937547,4.408950e+06
19477,India,IND,1770,31692.695,36060.594,8658843.00,431822.25000,999177.10,126513.8000,498799.970,0.0,1781.6083,540777.937547,4.408950e+06
19478,India,IND,1780,32308.560,36686.246,8808680.00,439267.25000,1016290.40,128685.0000,508781.620,0.0,1781.6083,540777.937547,4.408950e+06
19479,India,IND,1790,32933.355,37311.703,8958415.00,446703.34000,1033367.50,130852.2100,518943.750,0.0,1781.6083,540777.937547,4.408950e+06
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35006,Qatar,QAT,2018,186914.970,405088.900,193344.39,678.72754,466816.03,2550.7607,8871.912,0.0,1781.6083,540777.937547,4.408950e+06
35007,Qatar,QAT,2019,192738.550,181869.050,194989.12,637.26920,468063.03,2340.4930,9093.083,0.0,1781.6083,540777.937547,4.408950e+06
35008,Qatar,QAT,2020,183791.970,183313.620,185905.12,600.25030,466069.78,2310.0417,9108.847,0.0,1781.6083,540777.937547,4.408950e+06
35009,Qatar,QAT,2021,189422.660,186768.880,188787.89,590.28400,466875.62,2295.4860,9304.514,0.0,1781.6083,540777.937547,4.408950e+06
35010,Qatar,QAT,2022,187883.860,192605.620,190705.08,599.88934,467818.16,2374.2583,9549.245,0.0,1781.6083,540777.937547,4.408950e+06